# Generated by Django 3.2 on 2021-05-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_beta_web_app', '0002_auto_20210501_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='display_image',
            field=models.FileField(upload_to='', verbose_name='Image'),
        ),
    ]
