# Django imports
from django.urls import path
# My apps imports
from sdu_beta_web_app.views import views_admin

urlpatterns = [
    path('home/', views_admin.admin_home, name="admin_home"),
    path('profile/', views_admin.admin_profile, name="admin_profile"),
    path('update_profile/', views_admin.update_admin_profile,
         name="update_admin_profile"),
    path('add_staff/', views_admin.add_staff, name="add_staff"),
    path('save_staff/', views_admin.save_staff, name="save_staff"),
    path('manage_staff/', views_admin.manage_staff, name="manage_staff"),
    path('edit_staff/<str:staff_id>/', views_admin.edit_staff, name="edit_staff"),
    path('update_staff/', views_admin.update_staff, name="update_staff"),
    path('delete_staff/<str:staff_id>',
         views_admin.delete_staff, name="delete_staff"),
    path('add_company/', views_admin.add_company, name="add_company"),
    path('save_company/', views_admin.save_company, name="save_company"),
    path('manage_company/', views_admin.manage_company, name="manage_company"),
    path('edit_company/<str:company_id>',
         views_admin.edit_company, name="edit_company"),
    path('update_company/', views_admin.update_company, name="update_company"),
    path('delete_company/<str:company_id>',
         views_admin.delete_company, name="delete_company"),
    path('add_student/', views_admin.add_student, name="add_student"),
    path('save_student/', views_admin.save_student, name="save_student"),
    path('manage_student/', views_admin.manage_student, name="manage_student"),
    path('edit_student/<str:student_id>/',
         views_admin.edit_student, name="edit_student"),
    path('update_student/', views_admin.update_student, name="update_student"),
    path('delete_student/<str:student_id>',
         views_admin.delete_student, name="delete_student"),
    path('feedback_messages/', views_admin.feedback_messages,
         name="feedback_messages"),
    path('feedback_reply/', views_admin.feedback_reply, name="feedback_reply"),
    path('set_end_date/', views_admin.set_end_date, name="set_end_date"),
    path('manage_registration/', views_admin.manage_registration,
         name="manage_registration"),
    path('reg_approve/<str:student_id>/',
         views_admin.reg_approve, name="reg_approve"),
    path('reg_reject/<str:student_id>/',
         views_admin.reg_reject, name="reg_reject"),
    path('reg_cancel/<str:student_id>/',
         views_admin.reg_cancel, name="reg_cancel"),
    path('reject_reply/', views_admin.reject_reply, name="reject_reply"),
    path('add_report/', views_admin.add_report, name="add_report"),
    path('save_report/', views_admin.save_report, name="save_report"),
    path('manage_report/', views_admin.manage_report, name="manage_report"),
    path('edit_report/<str:report_id>',
         views_admin.edit_report, name="edit_report"),
    path('update_report/', views_admin.update_report, name="update_report"),
    path('delete_report/<str:report_id>',
         views_admin.delete_report, name="delete_report"),
    path('view_report/<str:report_id>/',
         views_admin.view_report, name="view_report"),
    path('set_grade/', views_admin.set_grade, name="set_grade"),
    path('grades/', views_admin.grades, name="grades"),
    path('view_grade/<str:student_id>/',
         views_admin.view_grade, name="view_grade"),
    path('set_final_grade/', views_admin.set_final_grade, name="set_final_grade"),
    path('reset_final_grade/', views_admin.reset_final_grade,
         name="reset_final_grade"),
]
